package com.example.demomarvel.ui.share.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFEC6A24)
val PurpleGrey80 = Color(0xFFEC6A24)
val Pink80 = Color(0xFFEC6A24)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


val md_theme_light_primary = Color(0xFFEC6A24)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCD)
val md_theme_light_onPrimaryContainer = Color(0xFF351000)
val md_theme_light_secondary = Color(0xFF705D00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE16F)
val md_theme_light_onSecondaryContainer = Color(0xFF221B00)
val md_theme_light_tertiary = Color(0xFFB82017)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onTertiaryContainer = Color(0xFF410000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB595)
val md_theme_light_surfaceTint = Color(0xFFA23F00)
val md_theme_light_outlineVariant = Color(0xFFD8C2BA)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFF181211)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4DED5)
val md_theme_light_onSurfaceVariant = Color(0xFF52443D)

val md_theme_dark_primary = Color(0xFFEC6A24)
val md_theme_dark_onPrimary = Color(0xFF571E00)
val md_theme_dark_primaryContainer = Color(0xFF7C2E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCD)
val md_theme_dark_secondary = Color(0xFFE3C54A)
val md_theme_dark_onSecondary = Color(0xFF3A3000)
val md_theme_dark_secondaryContainer = Color(0xFF544600)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE16F)
val md_theme_dark_tertiary = Color(0xFFFFB4A9)
val md_theme_dark_onTertiary = Color(0xFF690001)
val md_theme_dark_tertiaryContainer = Color(0xFF930003)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFA23F00)
val md_theme_dark_surfaceTint = Color(0xFFFFB595)
val md_theme_dark_outlineVariant = Color(0xFF52443D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF181211)
val md_theme_dark_onSurface = Color(0xFFD0C4C2)
val md_theme_dark_surfaceVariant = Color(0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BA)


val seed = Color(0xFFEC6A24)